### ISSUE TITLE
Kilo to Liberty Upgrade failed at repobuild

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1078]
##### What version (commit) do you encounter this issue on?

r12.1.1

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

repo build process does not break during the upgrade.sh script

##### What is actually happening?

```
TASK: [repo_build | Create OpenStack-Ansible requirement wheels] **************
failed: [infra01_repo_container-e3080f30] => {"changed": true, "cmd": "pip wheel --timeout 120 --wheel-dir /tmp/openstack-wheel-output --allow-all-external --find-links /tmp/openstack-wheel-output --
constraint /var/www/repo/os-releases/12.0.13/requirements_constraints.txt --index-url https://rpc-repo.rackspace.com/pools --trusted-host rpc-repo.rackspace.com --extra-index-url https://pypi.python.org/sim
ple --trusted-host pypi.python.org --build /tmp/openstack-builder --log /var/log/repo/repo_builder.log --requirement /var/www/repo/os-releases/12.0.13/requirements_local_filtered.txt", "delta": "0:00:02.494
133", "end": "2016-05-13 10:47:35.450427", "rc": 1, "start": "2016-05-13 10:47:32.956294", "warnings": []}
stderr: DEPRECATION: --allow-all-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
Ignoring dnspython3: markers u"python_version=='3.4'" don't match your environment
Note: checking out '62b18d667064506b3f8f62653fc0b8662b41ebf5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

  Could not find a tag or branch '62b18d667064506b3f8f62653fc0b8662b41ebf5', assuming commit.
Command "python setup.py egg_info" failed with error code 1 in /tmp/openstack-builder/aodh/
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
stdout: Collecting aodh from git+file:///var/www/repo/openstackgit/aodh@62b18d667064506b3f8f62653fc0b8662b41ebf5#egg=aodh (from -c /var/www/repo/os-releases/12.0.13/requirements_constraints.txt (line 2))
  Cloning file:///var/www/repo/openstackgit/aodh (to 62b18d667064506b3f8f62653fc0b8662b41ebf5) to /tmp/openstack-builder/aodh
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/pbr/core.py", line 109, in pbr
        attrs = util.cfg_to_args(path)
      File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 261, in cfg_to_args
        wrap_commands(kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 482, in wrap_commands
        for cmd, _ in dist.get_command_list():
      File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 447, in get_command_list
        cmdclass = ep.resolve()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/local/lib/python2.7/dist-packages/pbr/testr_command.py", line 47, in <module>
        from testrepository import commands
    ImportError: No module named testrepository
    error in setup command: Error parsing /tmp/openstack-builder/aodh/setup.cfg: ImportError: No module named testrepository

    ----------------------------------------

FATAL: all hosts have already failed -- aborting

    ----------------------------------------

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
repo_build | Create OpenStack global requirements wheels -------------- 230.72s
repo_build | Clone all upstream git repositories ----------------------- 66.74s
memcached_server | Update apt sources ----------------------------------- 8.92s
Wait for container ssh -------------------------------------------------- 5.46s
repo_build | Install pip packages --------------------------------------- 3.85s
repo_server | Install apt packages -------------------------------------- 3.47s
repo_build | Create OpenStack-Ansible requirement wheels ---------------- 2.59s
pip_install | Install PIP ----------------------------------------------- 1.31s
repo_server | Create authorized keys file from host vars ---------------- 1.18s
repo_server | File and directory setup ---------------------------------- 1.07s
           to retry, use: --limit @/root/setup-infrastructure.retry

infra01_memcached_container-9fd1b824 : ok=9    changed=4    unreachable=0    failed=0
infra01_repo_container-e3080f30 : ok=78   changed=31   unreachable=0    failed=1
infra02_memcached_container-6af94e74 : ok=9    changed=4    unreachable=0    failed=0
infra02_repo_container-c32af837 : ok=56   changed=19   unreachable=0    failed=0
infra03_memcached_container-646f6c2c : ok=9    changed=4    unreachable=0    failed=0
infra03_repo_container-3aad1fa6 : ok=56   changed=20   unreachable=0    failed=0

ran setup-infrastructure.yml -e 'galera_upgrade=true' -e 'rabbitmq_upgrade=true'
******************** failure ********************
The upgrade script has encountered a failure.
Failed on task setup-infrastructure.yml -e 'galera_upgrade=true' -e 'rabbitmq_upgrade=true'
Re-run the run-upgrade.sh script, or
execute the remaining tasks manually:
openstack-ansible  -e 'pip_install_options=--force-reinstall'
openstack-ansible  -e 'pip_install_options=--force-reinstall'
openstack-ansible  -e 'pip_install_options=--force-reinstall'
openstack-ansible  -e 'pip_install_options=--force-reinstall'
openstack-ansible setup-hosts.yml --limit '!galera_all[0]' -e 'pip_install_options=--force-reinstall'
openstack-ansible lxc-containers-create.yml --limit galera_all[0] -e 'pip_install_options=--force-reinstall'
openstack-ansible  -e 'pip_install_options=--force-reinstall'
openstack-ansible setup-infrastructure.yml -e 'galera_upgrade=true' -e 'rabbitmq_upgrade=true' -e 'pip_install_options=--force-reinstall'
openstack-ansible /opt/rpc-openstack/openstack-ansible/scripts/upgrade-utilities/playbooks/disable-neutron-port-security.yml -e 'pip_install_options=--force-reinstall'
openstack-ansible /opt/rpc-openstack/openstack-ansible/scripts/upgrade-utilities/playbooks/memcached-flush.yml -e 'pip_install_options=--force-reinstall'
openstack-ansible setup-openstack.yml -e 'pip_install_options=--force-reinstall'
openstack-ansible /opt/rpc-openstack/openstack-ansible/scripts/upgrade-utilities/playbooks/cleanup-rabbitmq-vhost.yml -e 'pip_install_options=--force-reinstall'
******************** failure ********************
```

##### How can we reproduce this issue?

N/A

##### How can we verify your issue is addressed?

Git issue is addressed

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2
- [ ] liberty-12.1
- [ ] kilo

**Comment by BjoernT** [comment]
So it seems the it is related to a strange SHA after doing a submodule init/update

/opt/rpc-openstack# git submodule status
+a60ad57f8cd35e57fb160ba5ea8fd190f6810ef3 openstack-ansible (12.0.12-15-ga60ad57)

I updated openstack-ansible now to the desired SHA d4e54bf and rerun the plays now

**Comment by git-harry** [comment]
A working upgrade from r11.1.8 to r12.1.1 was performed yesterday by the periodic upgrade matrix job http://jenkins.propter.net/job/RPC-AIO/5732/

**Comment by BjoernT** [comment]
Closing out since I was not able to reproduce it. We will add a git check to verify the correct sha
