### ISSUE TITLE
No multiline stitching  on Openstack Error messages

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1166]
##### What version (commit) do you encounter this issue on?

All

##### What type of issue is this (bug, feature, documentation, regression)?

Feature

##### What is the expected behavior?

It would be nice to have the Openstack related errors parsed as one document rather than each single line is a document for those errors like:

```
2016-06-15 04:25:03.387 800 WARNING cinder.volume.api [req-f460c91c-3cda-45ba-bb7d-70ea3fa753d6 176bdfb976b34e4fbb43cfac8275e2cc fb9de3725cc04dbdb099a367d3291060 - - -] Task 'cinder.volume.flows.api.create_
volume.ExtractVolumeRequestTask;volume:create'' (1dbe287a-f43e-43e6-906f-da81f4f1eba8) transitioned into state 'FAILURE' from state 'RUNNING'
1 predecessors (most recent atoms first):
  volume_create_api
2016-06-15 04:25:03.387 800 ERROR cinder.volume.api Traceback (most recent call last):
2016-06-15 04:25:03.387 800 ERROR cinder.volume.api   File "/openstack/venvs/cinder-12.0.10/lib/python2.7/site-packages/taskflow/engines/action_engine/executor.py", line 82, in _execute_task
2016-06-15 04:25:03.387 800 ERROR cinder.volume.api     result = task.execute(**arguments)
2016-06-15 04:25:03.387 800 ERROR cinder.volume.api   File "/openstack/venvs/cinder-12.0.10/lib/python2.7/site-packages/cinder/volume/flows/api/create_volume.py", line 377, in execute
2016-06-15 04:25:03.387 800 ERROR cinder.volume.api     source_volume)
2016-06-15 04:25:03.387 800 ERROR cinder.volume.api   File "/openstack/venvs/cinder-12.0.10/lib/python2.7/site-packages/cinder/volume/flows/api/create_volume.py", line 294, in _extract_availability_zone
2016-06-15 04:25:03.387 800 ERROR cinder.volume.api     raise exception.InvalidInput(reason=msg)
2016-06-15 04:25:03.387 800 ERROR cinder.volume.api InvalidInput: Invalid input received: Availability zone 'AZ1' is invalid.
2016-06-15 04:25:03.387 800 ERROR cinder.volume.api
```

##### What is actually happening?

Each line of a OpenStack error message is produced into a ES documents

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

-

##### How can we reproduce this issue?

-

##### How can we verify your issue is addressed?

See above

##### What is your evaluation on the importance of this issue, and why?

Prio 3

###### Remove branches (lines) you do not wish to target.
- [ ] Master
- [ ] liberty-12.2

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

**Comment by mancdaz** [comment]
@odyssey4me isn't beaver meant to take care of this?

**Comment by git-harry** [comment]
@mancdaz I was under the impression that there was some form of multiline support. r13 will be replacing beaver with filebeat, @d34dh0r53 maybe you could provide a comment on how this change will impact any multiline support that we may currently have.

**Comment by odyssey4me** [comment]
@mancdaz It would appear that the message format may have changed. In https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/beaver.yml#L24-L49 there is regex detection of multiline TRACE messages for some services. That may have to be updated.

**Comment by d34dh0r53** [comment]
Yep, looks like `TRACE` was replaced with `ERROR` on some services at least.  The refresh will have full multiline capabilities like we do with beaver.

**Comment by AlexeyDushechkin** [comment]
It was done in oslo.log (https://review.openstack.org/#/c/166537/) and really made my life harder. One can't simply replace TRACE with ERROR and be happy because all errors will obviously be merged with previous innocent log messages. I ended up with replacing logging_exception_prefix in all services to the old value with TRACE (like devstack, actually) and 150+ symbol multiline_regex_before in beaver which may shortly be described as `^((ISO8601DATE PID TRACE)|(?!ISO8601DATE))`. Second part is necessary for merging some nova-compute traces/debug output with subsequent lines doesn't starting with a date.

There are actually some TRACE severity messages at least in Keystone, but I decided to ignore them because I don't see any real life reason to enable that level of logging.

.
