### ISSUE TITLE
The horizon-extensions upgrade fails on repo-build

### ISSUE THREAD

**Issue by d34dh0r53** [rcbops/rpc-openstack#1345]
##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
The horizon-extensions pip should build correctly

##### What is actually happening?
```
Collecting horizon_extensions from git+file:///var/www/repo/openstackgit/horizon-extensions@master#egg=horizon_extensions&gitname=horizon-extensions&projectgroup=all&subdirectory=horizon-extensions/ (from -c /var/www/repo/os-releases/13.3.1/requirements_constraints.txt (line 11))
  Cloning file:///var/www/repo/openstackgit/horizon-extensions (to master) to /tmp/openstack-builder/horizon-extensions
  Running command git clone -q file:///var/www/repo/openstackgit/horizon-extensions /tmp/openstack-builder/horizon-extensions
  Running command git show-ref
  fb690bc528499bbf9aebba3ab0cce0b4dffd9e35 refs/heads/master
  fb690bc528499bbf9aebba3ab0cce0b4dffd9e35 refs/remotes/origin/HEAD
  fb690bc528499bbf9aebba3ab0cce0b4dffd9e35 refs/remotes/origin/master
  b9b7a9acd9947ae5a0b12f195a136515b9d5e737 refs/tags/10.0.0rc1
  fe79499dc554a98c0c32d587541335e01309443d refs/tags/10.0.0rc4
  ca1bff63690919ec3ae76e5cffd502379343dceb refs/tags/10.0.0rc5
  1a41afa384800f7b13433560e664c536236a1c36 refs/tags/11.0.0rc1
  d2ddea42ca66f251555dde7d7dcc02e34ecadb76 refs/tags/11.0.0rc2
  25603468347d2adca40f99b1e1d1601feb4e2b2b refs/tags/11.0.0rc3
  d12619e468c6c0ae33245ce8a6d70fdd51358cd6 refs/tags/11.0.0rc4
  d0a8fa7831b5560903d8a7def88d0763511849ae refs/tags/11.0.0rc5
  3a3f0e9a71558a5877250e608407ab3bc538493e refs/tags/9.0.1
  a3378af1c5a6ce66f7a2f76f23facb149090e931 refs/tags/r11.0.0
  7d1c13964e5068805910c9def7ea53e6962f7060 refs/tags/r11.0.0rc10
  943bea7e3005beb6422c7851f1c4cdeb767f2dea refs/tags/r11.0.0rc11
  c2a11b3aa7922be39586dd5a306a23be6b193d0e refs/tags/r11.0.0rc12
  45014808917888033c81f75b52e1269d2c3e9fe3 refs/tags/r11.0.0rc13
  2a20c59e72c20ee6262214265a5b8de0f95baf5f refs/tags/r11.0.0rc14
  d2ec4e668219cb1baba327dcc602c72e3bbed46b refs/tags/r11.0.0rc15
  2b9e141fe10bd98df728d9b3cc0b9199773fdefa refs/tags/r11.0.0rc16
  1e9f8fb02837c18c7f2c090147f0e3bbdb19738c refs/tags/r11.0.0rc17
  90ad9017b412809bd9c4740678bc5ae3ea1cb376 refs/tags/r11.0.0rc18
  d0a8fa7831b5560903d8a7def88d0763511849ae refs/tags/r11.0.0rc5
  0e8cfaf663e85353865b82a27c3b91480c9f5122 refs/tags/r11.0.0rc6
  3df4cb2c405fb77d578f5b30e66ccc95de74e05a refs/tags/r11.0.0rc7
  317ad5ccdf1e05bea11252b25b1c3f3bfb539f19 refs/tags/r11.0.0rc8
  aa3d40931d7f3be0432e84608af9ee06ac26a3d2 refs/tags/r11.0.0rc9
  3e7d765e4ca5ddd195d60d4af42df4441768cb28 refs/tags/r11.0.1
  c7a505cf11db1cb03a24b0f16d9ce7be2a25325e refs/tags/r11.0.2
  ac160bf38177922712f201ddee446cb45a53141d refs/tags/r11.0.3
  b549a34401068229a22683ed5ea446343d952fee refs/tags/r11.0.4
  edd7c572944a2124277b1497f1fcaf842f6d81d9 refs/tags/r11.1.0
  e4fd0a26ec406c8fbcd766a308d0037a781a2c28 refs/tags/r11.1.0rc1
  8a5951d920aa4f5bb83e2892974f0c4911bc94de refs/tags/r11.1.0rc2
  f20580316a42251075db34daec2a13dae04c2cf7 refs/tags/r11.1.0rc3
  3a2c31bea838206947885b8b444fcf60254dc7bd refs/tags/r11.1.0rc4
  596791cd8fbaa5960455c8a147b83cd4a250b829 refs/tags/r11.1.0rc5
  50580f0c7b1e36824634e46318e980be26af7c10 refs/tags/r11.1.1
  111dc2e0a83eccd0cda2ad947da9a16c7d93301e refs/tags/r11.1.10
  b5cdb0f3837102afa68182249be5304240668f04 refs/tags/r11.1.11
  d531b5034e886959fd13c4600cf107d4f7062d10 refs/tags/r11.1.12
  befa0e9057398d1d923f29eeb401cd6cf686347b refs/tags/r11.1.13
  b885c4a8c5eef784af36f399614b89bcd53d6dc9 refs/tags/r11.1.14
  9c89cb68a2a9e410af74d1ddc6101129f5380798 refs/tags/r11.1.2
  d1d453cd49cc32be080c43f7a3cd50438b3a1a3f refs/tags/r11.1.3
  fe91825d83a73687b1c84fc7c0c2d9ebecc1c749 refs/tags/r11.1.4
  b712aaf831d4ec5a33bcda430b038c76d87194ec refs/tags/r11.1.5
  1d844eae4962ea61a1b76d8fd3914a668bd9210f refs/tags/r11.1.6
  2ee21461b698931cb511def8d878f7840bc86677 refs/tags/r11.1.7
  a468295a3802f61c1ba8ea275ebe1789f83de871 refs/tags/r11.1.8
  c4b7be004eeb11fdbe5c1ceb6b17a8103f89d53b refs/tags/r11.1.9
  f3bb95dd966a7f90ea1ca41f17d64c6064f49b28 refs/tags/r12.0.0rc1
  6e2ae8eae1d9e1fe9ee5dd5fe07ae3ce55808f0d refs/tags/r12.2.0
  26747f28ea081bf701f11348608ce30791e2c37b refs/tags/r12.2.0rc1
  2a54bd94f68fe2cb94b71844f02ee8bfa89eb6a6 refs/tags/r12.2.0rc2
  60e81a2cc44141bff77a08499d131a1b020108b3 refs/tags/r12.2.0rc3
  50cd6e67c6d83ede93eec081f6f133c9a2b5bb7f refs/tags/r12.2.0rc4
  a1b236661428eca90ec543c749f6e21ed465f7bd refs/tags/r12.2.1
  bc0424176ad2e0ae4c13e55f343d2303db43208b refs/tags/r12.2.2
  766e8c32a266f4c4cb372f9b3bd35fcd070883d0 refs/tags/r12.2.3
  aaaaaa3873bad545e6b9beee1d7f3b8ecb982aac refs/tags/r13.0.0rc1
  b017df8fc4a6a6f8171c8aae6d6d36597d1f6128 refs/tags/v9.0.0
  b017df8fc4a6a6f8171c8aae6d6d36597d1f6128 refs/tags/v9.0.0rc1
  Running command git rev-parse HEAD
  fb690bc528499bbf9aebba3ab0cce0b4dffd9e35
  Running setup.py (path:/tmp/openstack-builder/horizon-extensions/horizon-extensions/setup.py) egg_info for package horizon-extensions
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/openstack-builder/horizon-extensions/horizon-extensions/setup.py'
Cleaning up...
  Removing source in /tmp/openstack-builder/aodh
  Removing source in /tmp/openstack-builder/ceilometer
  Removing source in /tmp/openstack-builder/cinder
  Removing source in /tmp/openstack-builder/glance
  Removing source in /tmp/openstack-builder/heat
  Removing source in /tmp/openstack-builder/horizon
Command "python setup.py egg_info" failed with error code 1 in /tmp/openstack-builder/horizon-extensions/horizon-extensions/
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/wheel.py", line 195, in run
    if not wb.build():
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 750, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 370, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 601, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 127, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 425, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 718, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/openstack-builder/horizon-extensions/horizon-extensions/
```
##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Upgrading RPC-O from Liberty `12.2.2` to Mitaka `13.0.0-rc1`

##### How can we reproduce this issue?
Use the `run-upgrade.sh` script or the manual processes outlined in the OSA docs to perform an upgrade on an RPCO environment.

##### How can we verify your issue is addressed?
Clean `repo-build.yml` output

##### What is your evaluation on the importance of this issue, and why?
I may be a bit ahead of the game but I thought I'd put this here to ensure that it doesn't get lost.
----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [x] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [x] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

rcbops/u-suk-dev#357
rcbops/horizon-extensions

**Comment by d34dh0r53** [comment]
@neillc and @r1chardj0n3s any ideas on this one?

**Comment by evrardjp** [comment]
Please read card https://github.com/rcbops/u-suk-dev/issues/199

**Comment by d34dh0r53** [comment]
@evrardjp removing the path to the previous version worked.

**Comment by major** [comment]
I'll see if I can wrangle a patch.
