### ISSUE TITLE
Allow overridable Tempest networking

### ISSUE THREAD

**Issue by jpmontez** [rcbops/rpc-openstack#1356]
##### On which version(s) do you encounter this issue?
r13.0.0rc1
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

```
root@627551-infra01:/opt/rpc-openstack# git describe --all
r13.0.0rc1
```

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
For the Tempest playbook to complete successfully — with the project installed and networking setup automatically.

##### What is actually happening?
The Tempest networking defaults are incompatible with our release labs. The flat networking rather than vxlan/vlan is used, therefore the following error message is returned:

```
22:21:46 TASK: [os_tempest | Ensure public network exists] ***************************** 
22:21:46 skipping: [627552-infra02_utility_container-e99285ef]
22:21:46 skipping: [627553-infra03_utility_container-ee0ef948]
22:21:47 failed: [627551-infra01_utility_container-aebe9553] => {"failed": true, "parsed": false}
22:21:47 OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
22:21:47 debug1: Reading configuration data /etc/ssh/ssh_config
22:21:47 debug1: /etc/ssh/ssh_config line 19: Applying options for *
22:21:47 debug1: auto-mux: Trying existing master
22:21:47 debug1: mux_client_request_session: master session id: 2
22:21:47 Traceback (most recent call last):
22:21:47   File "<stdin>", line 2034, in <module>
22:21:47   File "<stdin>", line 2031, in main
22:21:47   File "<stdin>", line 1799, in command_router
22:21:47   File "<stdin>", line 1927, in _create_network
22:21:47   File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 97, in with_params
22:21:47     ret = self.function(instance, *args, **kwargs)
22:21:47   File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 681, in create_network
22:21:47     return self.post(self.networks_path, body=body)
22:21:47   File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 363, in post
22:21:47     headers=headers, params=params)
22:21:47   File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 298, in do_request
22:21:47     self._handle_fault_response(status_code, replybody, resp)
22:21:47   File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 273, in _handle_fault_response
22:21:47     exception_handler_v20(status_code, error_body)
22:21:47   File "/usr/local/lib/python2.7/dist-packages/neutronclient/v2_0/client.py", line 84, in exception_handler_v20
22:21:47     request_ids=request_ids)
22:21:47 neutronclient.common.exceptions.BadRequest: Invalid input for operation: Flat provider networks are disabled.
22:21:47 Neutron server returns request_ids: ['req-7a1cb37a-169d-4cce-905a-fc69691541a2']
```
##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Run the `os-tempest-install.yml` playbook.

##### How can we reproduce this issue?

Run the `os-tempest-install.yml` playbook in an environment that doesn't have flat networking.

##### How can we verify your issue is addressed?

By logging onto the device and running the playbook with a fix overlayed.

##### If you are using or know of a workaround please describe the necessary steps?

- Bump the SHA of Tempest to at least [`403fcf8e19af9dd37ca4a8cc0faf222aeae4fa52`](https://github.com/openstack/openstack-ansible-os_tempest/commit/403fcf8e19af9dd37ca4a8cc0faf222aeae4fa52)
- Because the Tempest SHA is bumped, the `allocation_pool` functionality is added into the `neutron` library. Therefore, `openstack-ansible-plugins` needs to be bumped to include SHAs [`4cd932ae7a52f011e0e291e03788af9c4026163d`](https://github.com/openstack/openstack-ansible-plugins/commit/4cd932ae7a52f011e0e291e03788af9c4026163d) and [`41778e3bf38e4e015199b7fcb9017d462cc197dc`](https://github.com/openstack/openstack-ansible-plugins/commit/41778e3bf38e4e015199b7fcb9017d462cc197dc).

With only a Tempest SHA bump:
```
TASK: [os_tempest | Ensure public subnet exists] ******************************
skipping: [627552-infra02_utility_container-e99285ef]
skipping: [627553-infra03_utility_container-ee0ef948]
failed: [627551-infra01_utility_container-aebe9553] => {"failed": true}
msg: unsupported parameter for module: allocation_pools

FATAL: all hosts have already failed -- aborting
```

Note: I'm not certain that the above SHA bumps would "rebuild" the requirements as needed so if someone can help clarify, I'd appreciate it.

##### What is your evaluation on the importance of this issue, and why?
Our test suite isn't compatible by default with our release labs. The QE workflow is therefore broken and requires workarounds.

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by git-harry** [comment]
@jpmontez https://github.com/openstack/openstack-ansible-os_tempest/commit/403fcf8e19af9dd37ca4a8cc0faf222aeae4fa52 is on the master branch of openstack-ansible-os_tempest and so it would need backporting to stable/mitaka. By the looks of it you need a couple of things backported, e.g. https://github.com/openstack/openstack-ansible-os_tempest/commit/f57ef996. Given that these commits seem to be written by your team and you are able to test this, would you mind checking what needs backporting to the role's stable/mitaka branch. Once we know what is needed we can work to get it merged upstream.

**Comment by jpmontez** [comment]
The following commits need to be back-ported in order:
- First, https://github.com/openstack/openstack-ansible-os_tempest/commit/f57ef996a28b0a34ca7427ba52876f33c47f7a4d
- Followed by https://github.com/openstack/openstack-ansible-os_tempest/commit/403fcf8e19af9dd37ca4a8cc0faf222aeae4fa52

Those two are a good starting point, but there's one more changes that are needed between the `openstack-ansible-os_tempest` role and `openstack-ansible-plugins`: the option to disable a Neutron router's HA feature. That's the last incompatibility that I can see from my tests.

**Comment by git-harry** [comment]
These two patches are required by QE to support their testing:
https://review.openstack.org/#/c/361128/
https://review.openstack.org/#/c/361129/

@jpmontez please 361129, which depends on 361128, to ensure the resultant code meets your requirements.
