### ISSUE TITLE
[Mitaka] - Glance is failing to upload images

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#1383]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.
r13.0.0rc2

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?
glance client can upload an image no matter the size or the backend store (swift)

##### What is actually happening?
glance is failing to upload any images

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 
Upload both a basic cirros image and the ubuntu image for our solutions tab

##### How can we reproduce this issue?
Install glance with a swift glance store backend and upload an image into glance
here is the image i was testing with
http://ab031d5abac8641e820c-98e3b8a8801f7f6b990cf4f6480303c9.r33.cf1.rackcdn.com/Ubuntu%2012.04%20Heat%20agents

##### How can we verify your issue is addressed?
glance successfully uploads the above image when swift is the glance store

##### If you are using or know of a workaround please describe the necessary steps?
none atm

##### What is your evaluation on the importance of this issue, and why?
this is a high priority issue as we cannot currently upload any images to glance when we are using swift as the store

Here is the return that i am getting when trying to upload an image

```
DEBUG:keystoneclient.session:REQ: curl -g -i -X PUT http://172.29.236.121:9292/v2/images/18c43fff-d128-484b-8c79-aadeb4c7eb67/file -H "User-Agent: python-glanceclient" -H "Content-Type: application/octet-stream" -H "X-Auth-Token: {SHA1}2584473b0b82ac2bcd7e5c3ffa51612b6b244fbd" -d '<generator object _chunk_body at 0x7f94ed021640>'
+------------------+--------------------------------------+
| Property         | Value                                |
+------------------+--------------------------------------+
| checksum         | None                                 |
| container_format | bare                                 |
| created_at       | 2016-09-06T18:24:19Z                 |
| disk_format      | qcow2                                |
| id               | 18c43fff-d128-484b-8c79-aadeb4c7eb67 |
| min_disk         | 0                                    |
| min_ram          | 0                                    |
| name             | Ubuntu 12.04 Heat agents             |
| owner            | 09457a78a0194c308c784f1bbc377fd3     |
| protected        | False                                |
| size             | None                                 |
| status           | queued                               |
| tags             | []                                   |
| updated_at       | 2016-09-06T18:24:19Z                 |
| virtual_size     | None                                 |
| visibility       | public                               |
+------------------+--------------------------------------+
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/shell.py", line 675, in main
    OpenStackImagesShell().main(argv)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/shell.py", line 606, in main
    args.func(client, args)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/common/utils.py", line 98, in func_wrapper
    return func(gc, args)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/v2/shell.py", line 84, in do_image_create
    do_image_upload(gc, args)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/v2/shell.py", line 323, in do_image_upload
    gc.images.upload(args.id, image_data, args.size)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/v2/images.py", line 215, in upload
    url = '/v2/images/%s/file' % image_id
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/adapter.py", line 185, in put
    return self.request(url, 'PUT', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/glanceclient/common/http.py", line 330, in request
    raise exc.CommunicationError(message=message)
CommunicationError: Error finding address for http://172.29.236.121:9292/v2/images/18c43fff-d128-484b-8c79-aadeb4c7eb67/file: Unable to establish connection to http://172.29.236.121:9292/v2/images/18c43fff-d128-484b-8c79-aadeb4c7eb67/file
Error finding address for http://172.29.236.121:9292/v2/images/18c43fff-d128-484b-8c79-aadeb4c7eb67/file: Unable to establish connection to http://172.29.236.121:9292/v2/images/18c43fff-d128-484b-8c79-aadeb4c7eb67/file
```

@sigmavirus24 is currently working with me in our SAT lab to dig deeper into what is causeing this issue

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] mitaka-13.0
- [ ] liberty-12.2
- [ ] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by jacobwagner** [comment]
So it looks like we are having haproxy issues but that is not the case as @sigmavirus24 was able to connect to the api directly using pdb. Ill let him elaborate when he is done with his deep dive

**Comment by sigmavirus24** [comment]
So Glance is configured to use swift in this lab.

By default, Glance should always create the container in swift for it's images, but what we're seeing is this:

```
2016-09-06 17:53:26.461 3050 ERROR swiftclient ClientException: Container HEAD failed: http://172.29.236.121:8080/v1/AUTH_2f5fc67322714fbb88a7eba6ce91de71/glance_images 404 Not Found
2016-09-06 17:53:26.461 3050 ERROR swiftclient
2016-09-06 17:53:26.463 3050 INFO glance_store._drivers.swift.store [req-cd1af75e-010d-4deb-8486-45684c3b2a33 dfcdc23a6e984f43a518af6bfac31a3b 09457a78a0194c308c784f1bbc377fd3 - - -] Creating swift container glance_images
2016-09-06 17:53:26.511 3050 INFO swiftclient [req-cd1af75e-010d-4deb-8486-45684c3b2a33 dfcdc23a6e984f43a518af6bfac31a3b 09457a78a0194c308c784f1bbc377fd3 - - -] REQ: curl -i http://172.29.236.121:8080/v1/AUTH_2f5fc67322714fbb88a7eba6ce91de71/glance_images -X PUT -H "Content-Length: 0" -H "X-Auth-Token: afcbf008961546
b3..."
2016-09-06 17:53:26.511 3050 INFO swiftclient [req-cd1af75e-010d-4deb-8486-45684c3b2a33 dfcdc23a6e984f43a518af6bfac31a3b 09457a78a0194c308c784f1bbc377fd3 - - -] RESP STATUS: 404 Not Found
2016-09-06 17:53:26.511 3050 INFO swiftclient [req-cd1af75e-010d-4deb-8486-45684c3b2a33 dfcdc23a6e984f43a518af6bfac31a3b 09457a78a0194c308c784f1bbc377fd3 - - -] RESP HEADERS: {u'Date': u'Tue, 06 Sep 2016 17:53:26 GMT', u'Content-Length': u'70', u'Content-Type': u'text/html; charset=UTF-8', u'X-Trans-Id': u'tx4692e7e0
8b574d3882cb8-0057cf0296'}
2016-09-06 17:53:26.512 3050 INFO swiftclient [req-cd1af75e-010d-4deb-8486-45684c3b2a33 dfcdc23a6e984f43a518af6bfac31a3b 09457a78a0194c308c784f1bbc377fd3 - - -] RESP BODY: <html><h1>Not Found</h1><p>The resource could not be found.</p></html>
2016-09-06 17:53:26.512 3050 ERROR swiftclient [req-cd1af75e-010d-4deb-8486-45684c3b2a33 dfcdc23a6e984f43a518af6bfac31a3b 09457a78a0194c308c784f1bbc377fd3 - - -] Container PUT failed: http://172.29.236.121:8080/v1/AUTH_2f5fc67322714fbb88a7eba6ce91de71/glance_images 404 Not Found  [first 60 chars of response] <html><h
1>Not Found</h1><p>The resource could not be found.<
2016-09-06 17:53:26.512 3050 ERROR swiftclient Traceback (most recent call last):
2016-09-06 17:53:26.512 3050 ERROR swiftclient   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/swiftclient/client.py", line 1565, in _retry
2016-09-06 17:53:26.512 3050 ERROR swiftclient     service_token=self.service_token, **kwargs)
2016-09-06 17:53:26.512 3050 ERROR swiftclient   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/swiftclient/client.py", line 976, in put_container
2016-09-06 17:53:26.512 3050 ERROR swiftclient     http_response_content=body)
2016-09-06 17:53:26.512 3050 ERROR swiftclient ClientException: Container PUT failed: http://172.29.236.121:8080/v1/AUTH_2f5fc67322714fbb88a7eba6ce91de71/glance_images 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<
2016-09-06 17:53:26.512 3050 ERROR swiftclient
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data [req-cd1af75e-010d-4deb-8486-45684c3b2a33 dfcdc23a6e984f43a518af6bfac31a3b 09457a78a0194c308c784f1bbc377fd3 - - -] Failed to upload image data due to internal error
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data Traceback (most recent call last):
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/api/v2/image_data.py", line 114, in upload
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     image.set_data(data, size)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/domain/proxy.py", line 195, in set_data
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     self.base.set_data(data, size)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/notifier.py", line 449, in set_data
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     _send_notification(notify_error, 'image.upload', msg)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     self.force_reraise()
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     six.reraise(self.type_, self.value, self.tb)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/notifier.py", line 396, in set_data
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     self.repo.set_data(data, size)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/api/policy.py", line 192, in set_data
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     return self.image.set_data(*args, **kwargs)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/quota/__init__.py", line 298, in set_data
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     self.image.set_data(data, size=size)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/location.py", line 426, in set_data
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     verifier=verifier)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance_store/backend.py", line 371, in add_to_backend
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     verifier)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance_store/backend.py", line 344, in store_add_to_backend
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     verifier=verifier)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance_store/capabilities.py", line 226, in op_checker
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     return store_op_fun(store, *args, **kwargs)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance_store/_drivers/swift/store.py", line 535, in add
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     manager.get_connection())
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance_store/_drivers/swift/store.py", line 743, in _create_container_if_missing
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data     raise glance_store.BackendException(msg)
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data BackendException: Failed to add container to Swift.
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data Got error from Swift: Container PUT failed: http://172.29.236.121:8080/v1/AUTH_2f5fc67322714fbb88a7eba6ce91de71/glance_images 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<.
2016-09-06 17:53:26.514 3050 ERROR glance.api.v2.image_data
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi [req-cd1af75e-010d-4deb-8486-45684c3b2a33 dfcdc23a6e984f43a518af6bfac31a3b 09457a78a0194c308c784f1bbc377fd3 - - -] Caught error: Failed to add container to Swift.
Got error from Swift: Container PUT failed: http://172.29.236.121:8080/v1/AUTH_2f5fc67322714fbb88a7eba6ce91de71/glance_images 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<.
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi Traceback (most recent call last):
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/common/wsgi.py", line 902, in __call__
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     request, **action_args)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/common/wsgi.py", line 941, in dispatch
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     return method(*args, **kwargs)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/common/utils.py", line 362, in wrapped
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     return func(self, req, *args, **kwargs)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/api/v2/image_data.py", line 249, in upload
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     self._restore(image_repo, image)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     self.force_reraise()
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     six.reraise(self.type_, self.value, self.tb)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/api/v2/image_data.py", line 114, in upload
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     image.set_data(data, size)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/domain/proxy.py", line 195, in set_data
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     self.base.set_data(data, size)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/notifier.py", line 449, in set_data
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     _send_notification(notify_error, 'image.upload', msg)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     self.force_reraise()
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     six.reraise(self.type_, self.value, self.tb)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/notifier.py", line 396, in set_data
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     self.repo.set_data(data, size)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/api/policy.py", line 192, in set_data
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     return self.image.set_data(*args, **kwargs)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/quota/__init__.py", line 298, in set_data
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     self.image.set_data(data, size=size)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance/location.py", line 426, in set_data
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     verifier=verifier)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance_store/backend.py", line 371, in add_to_backend
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     verifier)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance_store/backend.py", line 344, in store_add_to_backend
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     verifier=verifier)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance_store/capabilities.py", line 226, in op_checker
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     return store_op_fun(store, *args, **kwargs)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance_store/_drivers/swift/store.py", line 535, in add
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     manager.get_connection())
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi   File "/openstack/venvs/glance-13.3.3/lib/python2.7/site-packages/glance_store/_drivers/swift/store.py", line 743, in _create_container_if_missing
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi     raise glance_store.BackendException(msg)
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi BackendException: Failed to add container to Swift.
2016-09-06 17:53:26.577 3050 ERROR glance.common.wsgi Got error from Swift: Container PUT failed: http://172.29.236.121:8080/v1/AUTH_2f5fc67322714fbb88a7eba6ce91de71/glance_images 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<.
```

Then eventlet drops the connection on the floor it seems which causes a "Broken pipe" error on the connection layer in the client which eventually bubbles up to the consumer as `Error finding address for http://172.29.236.121:9292/v2/images/18c43fff-d128-484b-8c79-aadeb4c7eb67/file: Unable to establish connection to http://172.29.236.121:9292/v2/images/18c43fff-d128-484b-8c79-aadeb4c7eb67/file`.

So the next step is to discover why Glance cannot create it's own container in Swift.

**Comment by sigmavirus24** [comment]
When we attempt to use glance's service credentials (which work against keystone) to upload the image directly, we get

```
swift upload glance_images Ubuntu\ 12.04\ Heat\ agents
Warning: failed to create container 'glance_images': 404 Not Found: <html><h1>Not Found</h1><p>The resource could not be found.<
```

**Comment by sigmavirus24** [comment]
So, swift seems to be unable to much of anything and looking at the proxy-error logs, we see:

```
Sep  3 17:27:34 node84-swift-proxy-container-ebea2a6b proxy-server: ERROR 500 Trying to PUT /AUTH_2f5fc67322714fbb88a7eba6ce91de71From Container Server 172.29.244.91:6002/sdd (txn: txa244f1898dca4e92a813a-0057cb0806) (client_ip: 172.29.237.62)
Sep  3 17:27:34 node84-swift-proxy-container-ebea2a6b proxy-server: ERROR 500 Trying to PUT /AUTH_2f5fc67322714fbb88a7eba6ce91de71From Container Server 172.29.244.93:6002/sdd (txn: txa244f1898dca4e92a813a-0057cb0806) (client_ip: 172.29.237.62)
Sep  3 17:27:34 node84-swift-proxy-container-ebea2a6b proxy-server: ERROR 500 Trying to PUT /AUTH_2f5fc67322714fbb88a7eba6ce91de71From Container Server 172.29.244.92:6002/sdd (txn: txa244f1898dca4e92a813a-0057cb0806) (client_ip: 172.29.237.62)
Sep  3 17:27:34 node84-swift-proxy-container-ebea2a6b proxy-server: ERROR 500 Trying to PUT /AUTH_2f5fc67322714fbb88a7eba6ce91de71From Container Server 172.29.244.91:6002/sdc (txn: txa244f1898dca4e92a813a-0057cb0806) (client_ip: 172.29.237.62)
Sep  3 17:27:34 node84-swift-proxy-container-ebea2a6b proxy-server: ERROR 500 Trying to PUT /AUTH_2f5fc67322714fbb88a7eba6ce91de71From Container Server 172.29.244.93:6002/sdc (txn: txa244f1898dca4e92a813a-0057cb0806) (client_ip: 172.29.237.62)
Sep  3 17:27:34 node84-swift-proxy-container-ebea2a6b proxy-server: ERROR 500 Trying to PUT /AUTH_2f5fc67322714fbb88a7eba6ce91de71From Container Server 172.29.244.92:6002/sdc (txn: txa244f1898dca4e92a813a-0057cb0806) (client_ip: 172.29.237.62)
Sep  3 17:27:34 node84-swift-proxy-container-ebea2a6b proxy-server: Container GET returning 503 for (503, 503, 503) (txn: txa244f1898dca4e92a813a-0057cb0806) (client_ip: 172.29.237.62)
Sep  3 17:27:34 node84-swift-proxy-container-ebea2a6b proxy-server: Could not autocreate account '/AUTH_2f5fc67322714fbb88a7eba6ce91de71' (txn: txa244f1898dca4e92a813a-0057cb0806) (client_ip: 172.29.237.62)
```

Which makes me think the container servers are totally busted.

**Comment by sigmavirus24** [comment]
```
Sep  3 17:25:43 node91 container-replicator: ERROR reading db /mnt/sde/containers/71/e62/03d3a76035bf0b74f493a28c98deae62/03d3a76035bf0b74f493a28c98deae62.db: #012Traceback (most recent call last):#012  File "/openstack/venvs/swift-13.3.3/lib/python2.7/site-packages/swift/common/db_replicator.py", line 479, in _replicate_object#012    now - (self.reclaim_age * 2))#012  File "/openstack/venvs/swift-13.3.3/lib/python2.7/site-packages/swift/common/db.py", line 813, in reclaim#012    with self.get() as conn:#012  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__#012    return self.gen.next()#012  File "/openstack/venvs/swift-13.3.3/lib/python2.7/site-packages/swift/common/db.py", line 366, in get#012    self.possibly_quarantine(*sys.exc_info())#012  File "/openstack/venvs/swift-13.3.3/lib/python2.7/site-packages/swift/common/db.py", line 338, in possibly_quarantine#012    six.reraise(exc_type, exc_value, exc_traceback)#012  File "/openstack/venvs/swift-13.3.3/lib/python2.7/site-packages/swift/common/db.py", line 364, in get#012    self.conn = get_db_connection(self.db_file, self.timeout)#012  File "/openstack/venvs/swift-13.3.3/lib/python2.7/site-packages/swift/common/db.py", line 194, in get_db_connection#012    timeout=timeout)#012DatabaseConnectionError: DB connection error (/mnt/sde/containers/71/e62/03d3a76035bf0b74f493a28c98deae62/03d3a76035bf0b74f493a28c98deae62.db, 25):#012Traceback (most recent call last):#012  File "/openstack/venvs/swift-13.3.3/lib/python2.7/site-packages/swift/common/db.py", line 175, in get_db_connection#012    factory=GreenDBConnection, timeout=timeout)#012  File "/openstack/venvs/swift-13.3.3/lib/python2.7/site-packages/swift/common/db.py", line 110, in __init__#012    super(GreenDBConnection, self).__init__(database, 0, *args, **kwargs)#012OperationalError: unable to open database file#012
```

Seems to be the refrain in container-error.log. I'm guessing the sqlite database is missing/cannot be created.

**Comment by sigmavirus24** [comment]
So we looked at some of the database files and they were not the permissions that swift was expecting. Some of the mount directories were "998" for user and group and others were "swift". I just tried chowning recursively to the "swift" user and group. Let's see what happens next.

**Comment by sigmavirus24** [comment]
Permissions on the mount directories was the problem. We were able to upload a small test file and glance image-upload seems to be working now.
