### ISSUE TITLE
MaaS plugins failing

### ISSUE THREAD

**Issue by git-harry** [rcbops/rpc-openstack#199]
The format of the token expiry string, returned by keystone, is different when using fernet tokens. This will break most/all of the OpenStack MaaS plugins. I've only tested this in master, but I think it will also affect kilo. I've logged a bug on launchpad [1] on the assumption this was not intentional.

./cinder_service_check.py --host 'maas2-node4' '172.29.236.3'
status error n.py", line 331, in is_token_expired\n    '%Y-%m-%dT%H:%M:%SZ')\n  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime\n    (data_string, format))\nValueError: time data '2015-06-28T05:01:12.403672Z' does not match format '%Y-%m-%dT%H:%M:%SZ'\n
Traceback (most recent call last):
  File "./cinder_service_check.py", line 88, in <module>
    main(args)
  File "./cinder_service_check.py", line 75, in main
    auth_ref = get_auth_ref()
  File "/usr/lib/rackspace-monitoring-agent/plugins/maas_common.py", line 341, in get_auth_ref
    if is_token_expired(auth_ref['token']):
  File "/usr/lib/rackspace-monitoring-agent/plugins/maas_common.py", line 331, in is_token_expired
    '%Y-%m-%dT%H:%M:%SZ')
  File "/usr/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '2015-06-28T05:01:12.403672Z' does not match format '%Y-%m-%dT%H:%M:%SZ'

[1] https://bugs.launchpad.net/keystone/+bug/1469458

**Comment by prometheanfire** [comment]
This is designated for 11.1 iirc, so tagging kilo backport

**Comment by nrb** [comment]
Bumping to prio-1 and r11.0.0rc9 per PR #286.

**Comment by nrb** [comment]
Merged into master and kilo
