### ISSUE TITLE
Liberty to Mitaka Upgrade: Cinder Backup Failures

### ISSUE THREAD

**Issue by mkam** [rcbops/rpc-openstack#2258]
> **THIS IS A PUBLIC FACING ISSUE.**
>
> Do not include private or confidential information in this issue.

## Is this a feature or a bug?

- [ ] Feature _(request for enhancement, new functionality)_
- [x] Bug _(something is broken)_

## Which version of rpc-openstack does this issue relate to?
- [ ] master
- [ ] newton-14.0
- [x] mitaka-13.1
- [x] liberty-12.2

Run `git log --pretty=oneline | head -n 1` and provide the output below between
the backtick lines:

```
b5c923bfc84efd398a531bc2e64721ca53be858d Remove old beaver checks/alarms (#2239)
```

## What happened?

After Liberty to Mitaka upgrades, creating a Cinder backup goes to ERROR.

```
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher [req-4380a894-c0e7-4443-b762-e465f2a4658f 24c3e10ba8214015bf77f570aeb20c04 f1bf681ae541467bbab2bb3869db41a6 - - -] Exception during message handling: One of cinder-volume services is too old to accept such request. Are you running mixed Liberty-Mitaka cinder-volumes?
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher Traceback (most recent call last):
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher   File "/openstack/venvs/cinder-13.3.19/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 138, in _dispatch_and_reply
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher     incoming.message))
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher   File "/openstack/venvs/cinder-13.3.19/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 185, in _dispatch
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher     return self._do_dispatch(endpoint, method, ctxt, args)
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher   File "/openstack/venvs/cinder-13.3.19/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 127, in _do_dispatch
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher     result = func(ctxt, **new_args)
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher   File "/openstack/venvs/cinder-13.3.19/lib/python2.7/site-packages/cinder/backup/manager.py", line 405, in create_backup
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher     self._update_backup_error(backup, context, six.text_type(err))
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher   File "/openstack/venvs/cinder-13.3.19/lib/python2.7/site-packages/oslo_utils/excutils.py", line 220, in __exit__
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher     self.force_reraise()
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher   File "/openstack/venvs/cinder-13.3.19/lib/python2.7/site-packages/oslo_utils/excutils.py", line 196, in force_reraise
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher     six.reraise(self.type_, self.value, self.tb)
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher   File "/openstack/venvs/cinder-13.3.19/lib/python2.7/site-packages/cinder/backup/manager.py", line 399, in create_backup
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher     self._run_backup(context, backup, volume)
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher   File "/openstack/venvs/cinder-13.3.19/lib/python2.7/site-packages/cinder/backup/manager.py", line 430, in _run_backup
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher     backup, volume)
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher   File "/openstack/venvs/cinder-13.3.19/lib/python2.7/site-packages/cinder/volume/rpcapi.py", line 407, in get_backup_device
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher     raise exception.ServiceTooOld(msg)
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher ServiceTooOld: One of cinder-volume services is too old to accept such request. Are you running mixed Liberty-Mitaka cinder-volumes?
2017-05-12 17:03:29.097 18227 ERROR oslo_messaging.rpc.dispatcher
```
I've occasionally seen this pass, but more often than not, it fails. My suspicion is that the cinder-backup service is not being restarted as the last service, which is the recommended order from the [Mitaka release notes](https://docs.openstack.org/releasenotes/cinder/mitaka.html#id8):

`As cinder-backup was strongly reworked in this release, the recommended upgrade order when executing live (rolling) upgrade is c-api->c-sch->c-vol->c-bak.`

When I restarted the backup service with `service cinder-backup restart`, I no longer saw the error. If it's a timing issue of the services coming up in particular order, that might also explain why it has a rare chance of passing.

## What were you doing when it happened?
Running cinder_backup tempest tests in gating periodic and PR jobs. The two tests that run for cinder_backup both fail with the same error.

```
tempest.api.volume.admin.test_volumes_backup.VolumesBackupsV1Test.test_volume_backup_create_get_detailed_list_restore_delete
tempest.api.volume.admin.test_volumes_backup.VolumesBackupsV2Test.test_volume_backup_create_get_detailed_list_restore_delete

Traceback (most recent call last):
  File "/opt/tempest_untagged/tempest/api/volume/admin/test_volumes_backup.py", line 57, in test_volume_backup_create_get_detailed_list_restore_delete
    'available')
  File "/opt/tempest_untagged/tempest/services/volume/base/base_backups_client.py", line 95, in wait_for_backup_status
    raise exceptions.VolumeBackupException(backup_id=backup_id)
tempest.exceptions.VolumeBackupException: Volume backup b62d71bc-05ec-4998-b833-fe578fd763c8 failed and is in ERROR status
```

## What did you expect to happen instead of what actually happened?
Backup is created successfully and tests pass.

## Do you think the documentation team wants to know about this?

- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

## Does your change require a release note?

- [ ] Yes, it's a pretty big deal like I am and I've made a reno note!
- [ ] Nope, this change has no major impact.

**Comment by mattt416** [comment]
Rather than reworking the sequence of cinder services being upgraded, perhaps we just add an upgrade task to run post-upgrade that restarts cinder-backup?
