### ISSUE TITLE
keystone_api_local_check failes when v3 enabled

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#495]
.//keystone_api_local_check.py   1.2.3.4

status error 7/dist-packages/keystoneclient/session.py", line 397, in request\n    raise exceptions.from_response(resp, method, url)\nUnauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-817c5f06-8d05-42ce-ac0e-82d1b05cb3e8)\n
Traceback (most recent call last):
  File "./keystone_api_local_check.py", line 77, in <module>
    main(args)
  File "./keystone_api_local_check.py", line 67, in main
    check(args)
  File "./keystone_api_local_check.py", line 51, in check
    user_count = len(keystone.users.list())
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/utils.py", line 318, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/v3/users.py", line 108, in list
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/base.py", line 73, in func
    return f(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/base.py", line 361, in list
    self.collection_key)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/base.py", line 113, in _list
    resp, body = self.client.get(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/adapter.py", line 170, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/adapter.py", line 206, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/adapter.py", line 95, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/utils.py", line 318, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneclient/session.py", line 397, in request
    raise exceptions.from_response(resp, method, url)
keystoneclient.openstack.common.apiclient.exceptions.Unauthorized: The request you have made requires authentication. (HTTP 401) (Request-ID: req-817c5f06-8d05-42ce-ac0e-82d1b05cb3e8)

This issue is present at RPC r11.0.0

**Comment by d34dh0r53** [comment]
Thanks @BjoernT

**Comment by BjoernT** [comment]
Tested this with LDAP and non LDAP setups.

**Comment by d34dh0r53** [comment]
Does this need to be backported?

**Comment by BjoernT** [comment]
No just kilo which we should cherry pick from here. Alternatively I can submit it for kilo

**Comment by BjoernT** [comment]
q

**Comment by d34dh0r53** [comment]
@BjoernT cherry-pick is fine

**Comment by rackertom** [comment]
@BjoernT If you're caught up doing other things we can do the cherry pick.

**Comment by BjoernT** [comment]
Per Dave, we should be ok to cherry pick.

**Comment by rackertom** [comment]
Cherry-pick is merged. Closing this issue.
