### ISSUE TITLE
Ceph Cinder Volume Creation Fails

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/rpc-openstack#747]
Creating a Ceph Cinder Volume fails with error: `Error: error calling conf_read_file: errno EACCES`

Ceph OSD Host -- `cinder-volume.log`

```
2016-01-17 01:39:39.655 25796 INFO cinder.volume.flows.manager.create_volume [req-0efef6a0-99bf-40f0-9991-088fd2acd953 e558bb61b8974f2f98f0cd7344bed2a8 c289b84b69434801a363fa8703f28a4e - - -] Volume 04d762cd-17c6-488a-b98e-7cd9417069ca: being created as raw with specification: {'status': u'creating', 'volume_size': 1, 'volume_name': u'volume-04d762cd-17c6-488a-b98e-7cd9417069ca'}
2016-01-17 01:39:39.688 25796 WARNING cinder.volume.manager [req-0efef6a0-99bf-40f0-9991-088fd2acd953 e558bb61b8974f2f98f0cd7344bed2a8 c289b84b69434801a363fa8703f28a4e - - -] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeFromSpecTask;volume:create' (8e671707-b9e6-4f58-adc6-793aa8c49769) transitioned into state 'FAILURE' from state 'RUNNING'
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager Traceback (most recent call last):
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager   File "/usr/local/lib/python2.7/dist-packages/taskflow/engines/action_engine/executor.py", line 67, in _execute_task
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager     result = task.execute(**arguments)
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/flows/manager/create_volume.py", line 639, in execute
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager     **volume_spec)
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/flows/manager/create_volume.py", line 613, in _create_raw_volume
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager     return self.driver.create_volume(volume_ref)
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager   File "/usr/local/lib/python2.7/dist-packages/osprofiler/profiler.py", line 105, in wrapper
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager     return f(*args, **kwargs)
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/drivers/rbd.py", line 518, in create_volume
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager     with RADOSClient(self) as client:
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/drivers/rbd.py", line 242, in __init__
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager     self.cluster, self.ioctx = driver._connect_to_rados(pool)
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager   File "/usr/local/lib/python2.7/dist-packages/cinder/volume/drivers/rbd.py", line 303, in _connect_to_rados
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager     conffile=self.configuration.rbd_ceph_conf)
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager   File "/usr/lib/python2.7/dist-packages/rados.py", line 253, in __init__
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager     self.conf_read_file(conffile)
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager   File "/usr/lib/python2.7/dist-packages/rados.py", line 302, in conf_read_file
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager     raise make_ex(ret, "error calling conf_read_file")
2016-01-17 01:39:39.688 25796 TRACE cinder.volume.manager Error: error calling conf_read_file: errno EACCES
```

The issue seems to be the permissions on `/etc/ceph`, which prevents `cinder-volume` from reading the necessary Ceph configs to perform the operation.

**Comment by byronmccollum** [comment]
Confirmed that changing permissions to something more permissive like 777 allows volumes to be created.

**Comment by byronmccollum** [comment]
This should do it...

```
chown root:cinder /etc/ceph
chmod g+x /etc/ceph
```

**Comment by BjoernT** [comment]
:-1:  The permissions should be 755 for the directory and 640 for the key. The keyfile is owned by root:cephkeys and cinder should be part of the cephkeys

**Comment by byronmccollum** [comment]
The permissions bounce back and forth between 755 and 644 depending on what playbook was last run.

```
rpcd:
  ceph-all.yml
    ceph-mon.yml
      ceph-mon role
        ceph-common role
          owner: root
          group: root
          mode:  644
    ceph-osd.yml
      ceph-osd role
        ceph-common role
          owner: root
          group: root
          mode:  644

openstack-ansible:
  setup-openstack.yml
    os-cinder-install.yml
      ceph_client role
        owner: root
        group: root
        mode:  0755
```

**Comment by BjoernT** [comment]
Yeah 644 is anyway wrong, if the permissions are used for directories. So we should use 755 here too

**Comment by byronmccollum** [comment]
644 is the default in the upstream `ceph-common` role. I just landed a patch upstream to make that configurable:

https://github.com/ceph/ceph-ansible/pull/485

Now we just need to pass `conf_directory_mode=755` when applying that role.

**Comment by BjoernT** [comment]
That's nice

**Comment by byronmccollum** [comment]
Found another discrepancy...if installing MaaS, it applies ceph-common and sets the permissions back to the defaults of 644.

```
rpcd:
  ceph-all.yml
    ceph-mon.yml
      ceph-mon role
        ceph-common role
          owner: root
          group: root
          mode:  0644
    ceph-osd.yml
      ceph-osd role
        ceph-common role
          owner: root
          group: root
          mode:  0644

openstack-ansible:
  setup-openstack.yml
    os-cinder-install.yml
      ceph_client role
        owner: root
        group: root
        mode:  0755
  setup-maas.yml
    ceph-common role
      owner: root
      group: root
      mode:  0644
```

**Comment by hughsaunders** [comment]
I have also seen this issue in RPC-AIO-ceph

```
2016-01-18 17:44:26.200 7260 INFO nova.compute.manager [req-dd271fc2-ba5d-481b-a286-2046e8256547 c027754222cd440980c6ce99bc579d4d 46af743d3d8548fbb4744cb833333435 - - -] [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] Starting instance...
2016-01-18 17:44:26.522 7260 INFO nova.compute.claims [req-dd271fc2-ba5d-481b-a286-2046e8256547 c027754222cd440980c6ce99bc579d4d 46af743d3d8548fbb4744cb833333435 - - -] [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] Attempting claim: memory 256 MB, disk 1 GB
2016-01-18 17:44:26.522 7260 INFO nova.compute.claims [req-dd271fc2-ba5d-481b-a286-2046e8256547 c027754222cd440980c6ce99bc579d4d 46af743d3d8548fbb4744cb833333435 - - -] [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] Total memory: 15035 MB, used: 2048.00 MB
2016-01-18 17:44:26.523 7260 INFO nova.compute.claims [req-dd271fc2-ba5d-481b-a286-2046e8256547 c027754222cd440980c6ce99bc579d4d 46af743d3d8548fbb4744cb833333435 - - -] [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] memory limit: 15035.00 MB, free: 12987.00 MB
2016-01-18 17:44:26.523 7260 INFO nova.compute.claims [req-dd271fc2-ba5d-481b-a286-2046e8256547 c027754222cd440980c6ce99bc579d4d 46af743d3d8548fbb4744cb833333435 - - -] [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] Total disk: 442 GB, used: 2.00 GB
2016-01-18 17:44:26.523 7260 INFO nova.compute.claims [req-dd271fc2-ba5d-481b-a286-2046e8256547 c027754222cd440980c6ce99bc579d4d 46af743d3d8548fbb4744cb833333435 - - -] [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] disk limit: 442.00 GB, free: 440.00 GB
2016-01-18 17:44:26.600 7260 INFO nova.compute.claims [req-dd271fc2-ba5d-481b-a286-2046e8256547 c027754222cd440980c6ce99bc579d4d 46af743d3d8548fbb4744cb833333435 - - -] [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] Claim successful
2016-01-18 17:44:26.934 7260 INFO nova.scheduler.client.report [req-dd271fc2-ba5d-481b-a286-2046e8256547 c027754222cd440980c6ce99bc579d4d 46af743d3d8548fbb4744cb833333435 - - -] Compute_service record updated for ('jrpcaio-459', 'jrpcaio-459')
2016-01-18 17:44:27.281 7260 INFO nova.scheduler.client.report [req-dd271fc2-ba5d-481b-a286-2046e8256547 c027754222cd440980c6ce99bc579d4d 46af743d3d8548fbb4744cb833333435 - - -] Compute_service record updated for ('jrpcaio-459', 'jrpcaio-459')
2016-01-18 17:44:27.300 7260 WARNING oslo_config.cfg [-] Option "username" from group "neutron" is deprecated. Use option "username" from group "neutron".
2016-01-18 17:44:27.667 7260 INFO nova.virt.libvirt.driver [req-dd271fc2-ba5d-481b-a286-2046e8256547 c027754222cd440980c6ce99bc579d4d 46af743d3d8548fbb4744cb833333435 - - -] [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] Creating image
2016-01-18 17:44:27.678 7260 ERROR nova.compute.manager [req-dd271fc2-ba5d-481b-a286-2046e8256547 c027754222cd440980c6ce99bc579d4d 46af743d3d8548fbb4744cb833333435 - - -] [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] Instance failed to spawn
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] Traceback (most recent call last):
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/local/lib/python2.7/dist-packages/nova/compute/manager.py", line 2473, in _build_resources
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     yield resources
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/local/lib/python2.7/dist-packages/nova/compute/manager.py", line 2345, in _build_and_run_instance
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     block_device_info=block_device_info)
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 2384, in spawn
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     admin_pass=admin_password)
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 2782, in _create_image
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     instance, size, fallback_from_host)
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/driver.py", line 5900, in _try_fetch_image_cache
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     size=size)
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/imagebackend.py", line 229, in cache
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     if not self.check_image_exists() or not os.path.exists(base):
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/imagebackend.py", line 714, in check_image_exists
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     return self.driver.exists(self.rbd_name)
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/rbd_utils.py", line 237, in exists
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     read_only=True):
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/rbd_utils.py", line 52, in __init__
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     client, ioctx = driver._connect_to_rados(pool)
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/local/lib/python2.7/dist-packages/nova/virt/libvirt/rbd_utils.py", line 110, in _connect_to_rados
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     conffile=self.ceph_conf)
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/lib/python2.7/dist-packages/rados.py", line 253, in __init__
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     self.conf_read_file(conffile)
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]   File "/usr/lib/python2.7/dist-packages/rados.py", line 302, in conf_read_file
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61]     raise make_ex(ret, "error calling conf_read_file")
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] Error: error calling conf_read_file: errno EACCES
2016-01-18 17:44:27.678 7260 TRACE nova.compute.manager [instance: 06f48c31-57e4-42e0-8baf-47a78c5ecb61] 
```

**Comment by prometheanfire** [comment]
now backport it :P

**Comment by byronmccollum** [comment]
@prometheanfire backport opened. also need #760 merged and backported to make it all work.

**Comment by d34dh0r53** [comment]
I believe everything has merged to fix this.
