### ISSUE TITLE
MaaS Common -- is_token_expired()

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/rpc-openstack#765]
This started breaking lots of MaaS plugins in r11.1.1...

```
# ./glance_api_local_check.py 172.29.237.1
status error ng-agent/plugins/maas_common.py", line 360, in get_auth_ref\n    if is_token_expired(auth_ref):\n  File "/usr/lib/rackspace-monitoring-agent/plugins/maas_common.py", line 338, in is_token_expired\n    token['token'].get('expires_at'))\nKeyError: 'token'\n
Traceback (most recent call last):
  File "./glance_api_local_check.py", line 97, in <module>
    main(args)
  File "./glance_api_local_check.py", line 86, in main
    auth_ref = get_auth_ref()
  File "/usr/lib/rackspace-monitoring-agent/plugins/maas_common.py", line 360, in get_auth_ref
    if is_token_expired(auth_ref):
  File "/usr/lib/rackspace-monitoring-agent/plugins/maas_common.py", line 338, in is_token_expired
    token['token'].get('expires_at'))
KeyError: 'token'
```

**Comment by BjoernT** [comment]
I have a proposal submitted to fix this via https://github.com/rcbops/rpc-openstack/pull/764/files
The originating error is inside the is_token_expired which checks for v3 and v2 token format at the same time, provoking the KeyError when looking for a v2 client response

**Comment by BjoernT** [comment]
I also added a retry for Unauthorized errors, which does trigger the retry logic

**Comment by d34dh0r53** [comment]
@BjoernT can you backport this please?
