### ISSUE TITLE
Exception from rpc-maas-tool.py

### ISSUE THREAD

**Issue by JCallicoat** [rcbops/rpc-openstack#848]
When you run rpc-maas-tool.py and the config file (.raxrc by default) does not contain a `[credentials]` section, a ConfigParser.NoSectionError is returned, but we are currently only catching ConfigParser.NoOptionError before trying the `[api]` section so it bombs out with a stack trace.

- [x] Master
- [x] liberty-12.0
- [x] kilo

**Comment by JCallicoat** [comment]
> Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1456108163.19-95784717954427/rpc-maas-tool.py", line 618, in <module>
    cli = RpcMassCli()
  File "/root/.ansible/tmp/ansible-tmp-1456108163.19-95784717954427/rpc-maas-tool.py", line 214, in __init__
    self.args.raxrcpath)
  File "/root/.ansible/tmp/ansible-tmp-1456108163.19-95784717954427/rpc-maas-tool.py", line 52, in __init__
    self._get_conn()
  File "/root/.ansible/tmp/ansible-tmp-1456108163.19-95784717954427/rpc-maas-tool.py", line 80, in _get_conn
    user = self.config.get('credentials', 'username')
  File "/usr/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'credentials'

**Comment by hughsaunders** [comment]
reopening for backports

**Comment by prometheanfire** [comment]
last one is to the liberty branch

**Comment by prometheanfire** [comment]
@rcbops/rax-qa can you reproduce this in a 12.0 lab?

**Comment by prometheanfire** [comment]
@rcbops/rax-qa ping?

**Comment by nrb** [comment]
@jacobwagner, @jpmontez, @tbyrom138

**Comment by d34dh0r53** [comment]
For docs this should be a 12.0 release note indicating this as a deficiency.

**Comment by xeregin** [comment]
Yes, it is present in our 12.0.0rc2 lab

**Comment by prometheanfire** [comment]
fixed
