### ISSUE TITLE
[r12.0.0rc2] Unable to build Cinder and Swift pip wheels

### ISSUE THREAD

**Issue by jpmontez** [rcbops/rpc-openstack#925]
##### What version (commit) do you encounter this issue on?
r12.0.0rc2

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
Build pip requirement wheels successfully

##### What is actually happening?
`pywbem` is failing to build, which is causing the wheels to fail, too.

##### How can we reproduce this issue?
Checkout the tag and run the deploy script.

##### How can we verify your issue is addressed?
The repo is available on QE's storage lab.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
Remove the `pywbem` requirement from the `os_cinder` and `os_swift` roles. This has already been done on the head of the Liberty branch.

##### What is your evaluation on the importance of this issue, and why?
It's moderately important because it causes builds to fail on this RC. It's not immediately pressing because there's a known fix.

##### What branches / milestones do you believe this issue should target?
- [ ] Master
- [x] liberty-12.0.0rc2

```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/openstack-builder/pywbem/setup.py", line 502, in <module>
      sys.exit(main())
    File "/tmp/openstack-builder/pywbem/setup.py", line 498, in main
      setup(**args)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/openstack-builder/pywbem/setup.py", line 293, in run
      pre_install(self.verbose, self.dry_run)
    File "/tmp/openstack-builder/pywbem/setup.py", line 309, in pre_install
      from pywbem import mof_compiler
    File "/tmp/openstack-builder/pywbem/pywbem/__init__.py", line 193, in <module>
      from .cim_operations import *
    File "/tmp/openstack-builder/pywbem/pywbem/cim_operations.py", line 47, in <module>
      from .cim_http import get_object_header, wbem_request, Error, AuthError, \
    File "/tmp/openstack-builder/pywbem/pywbem/cim_http.py", line 52, in <module>
      from M2Crypto import SSL
  ImportError: No module named M2Crypto

  ----------------------------------------
  Running setup.py bdist_wheel for ansible
  Stored in directory: /tmp/openstack-wheel-output
  Running setup.py bdist_wheel for M2Crypto
  Stored in directory: /tmp/openstack-wheel-output
Successfully built aodh ceilometer cinder glance heat horizon keystone neutron neutron-lbaas nova swift ansible-lint networking-plumgrid ansible M2Crypto
Failed to build pywbem
```

**Comment by tbyrom138** [comment]
For noting: this was not an issue earlier in QE testing.  This just popped up 2 days ago.

**Comment by d34dh0r53** [comment]
I believe this is resolved upstream, will link the bug when I find it.

**Comment by d34dh0r53** [comment]
This is resolved here [`4e8992`](http://git.openstack.org/cgit/openstack/openstack-ansible/commit/?h=liberty&id=4e89921b9d35fbb27b2cdd733c75d30b0e61e957) and will be fixed with the RC3 SHA bump.
