### ISSUE TITLE
horizon layout is wrong. please check the screenshot.

### ISSUE THREAD

**Issue by weezer** [rcbops/rpc-openstack#947]
##### What version (commit) do you encounter this issue on?
12.0.0rc4
##### What type of issue is this (bug, feature, documentation, regression)?
bug
##### What is the expected behavior?
different tab should have different layout, not all in one page
##### What is actually happening?
open horizon dashboard by browser.
##### How can we reproduce this issue?
rpc lab, actually qe-iad3-2
##### How can we verify your issue is addressed?
tab has it own layout.
##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [ ] liberty-12.0

![launch instance openstack dashboard](https://cloud.githubusercontent.com/assets/7200779/14188361/6d68ec98-f74d-11e5-8c7d-6d31d9baf46f.png)

![screen shot 2016-03-31 at 2 56 39 pm](https://cloud.githubusercontent.com/assets/7200779/14189056/fc64c356-f750-11e5-9eb5-db0d44e4aa4d.png)

**Comment by jacobwagner** [comment]
This may be releated to https://github.com/rcbops/rpc-openstack/issues/938

**Comment by weezer** [comment]
504f005e33bc.js:652 JQMIGRATE: Logging is active
launch:1225 Uncaught TypeError: Cannot read property 'workflow_init' of undefined
504f005e33bc.js:905 Uncaught Error: [$injector:modulerr] Failed to instantiate module horizon.app due to:
Error: [$injector:modulerr] Failed to instantiate module horizon.dashboard.rackspace due to:
Error: [$injector:nomod] Module 'horizon.dashboard.rackspace' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.7/$injector/nomod?p0=horizon.dashboard.rackspace
    at https://localhost:4443/static/dashboard/js/504f005e33bc.js:699:8
    at https://localhost:4443/static/dashboard/js/504f005e33bc.js:805:59
    at ensure (https://localhost:4443/static/dashboard/js/504f005e33bc.js:803:294)
    at module (https://localhost:4443/static/dashboard/js/504f005e33bc.js:805:8)
    at https://localhost:4443/static/dashboard/js/504f005e33bc.js:903:35
    at forEach (https://localhost:4443/static/dashboard/js/504f005e33bc.js:705:400)
    at loadModules (https://localhost:4443/static/dashboard/js/504f005e33bc.js:902:63)
    at https://localhost:4443/static/dashboard/js/504f005e33bc.js:903:84
    at forEach (https://localhost:4443/static/dashboard/js/504f005e33bc.js:705:400)
    at loadModules (https://localhost:4443/static/dashboard/js/504f005e33bc.js:902:63)
http://errors.angularjs.org/1.3.7/$injector/modulerr?p0=horizon.dashboard.r…%2Flocalhost%3A4443%2Fstatic%2Fdashboard%2Fjs%2F504f005e33bc.js%3A902%3A63)
    at https://localhost:4443/static/dashboard/js/504f005e33bc.js:699:8
    at https://localhost:4443/static/dashboard/js/504f005e33bc.js:905:7
    at forEach (https://localhost:4443/static/dashboard/js/504f005e33bc.js:705:400)
    at loadModules (https://localhost:4443/static/dashboard/js/504f005e33bc.js:902:63)
    at https://localhost:4443/static/dashboard/js/504f005e33bc.js:903:84
    at forEach (https://localhost:4443/static/dashboard/js/504f005e33bc.js:705:400)
    at loadModules (https://localhost:4443/static/dashboard/js/504f005e33bc.js:902:63)
    at createInjector (https://localhost:4443/static/dashboard/js/504f005e33bc.js:891:360)
    at doBootstrap (https://localhost:4443/static/dashboard/js/504f005e33bc.js:781:36)
    at bootstrap (https://localhost:4443/static/dashboard/js/504f005e33bc.js:782:58)
http://errors.angularjs.org/1.3.7/$injector/modulerr?p0=horizon.app&p1=Erro…%2Flocalhost%3A4443%2Fstatic%2Fdashboard%2Fjs%2F504f005e33bc.js%3A782%3A58)
2f52eee33079.js:3468 Uncaught TypeError: Cannot read property 'truncate' of undefined

**Comment by jacobwagner** [comment]
Yeah this is related to #938, closing
